version: "3.7"

services:
  rails:
    build: .
    restart: always
    networks:
      - infra_internal
      - traefik
    ports:
      - 3000
    entrypoint: [./bin/entry]
    command: bundle exec puma -C config/puma.rb
    environment:
      DATABASE_URL: p
      SECRET_KEY_BASE: C
      RAILS_DEVELOPMENT_HOSTS: v
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: TRUE
    labels:
      - traefik.http.routers.cryptol-rails.tls=true
      - traefik.http.routers.cryptol-rails.rule=Host(`v
    volumes:
      - .:/app

  sidekiq:
    build: .
    restart: always
    networks:
      - infra_internal
      - traefik
    command: bundle exec sidekiq
    environment:
      DATABASE_URL: p
      SECRET_KEY_BASE: C
      REDIS_URL: r
      REDIS_PROVIDER: REDIS_URL
      RAILS_LOG_TO_STDOUT: TRUE
    volumes:
      - .:/app

networks:
  infra_internal:
    external: true
  traefik:
    external: true
